#! /bin/bash
#
gfortran   invar.f90
gfortran   solvar.f90
gfortran   ahotn_kernel_module.f90
gfortran   timevar.f90
gfortran   main.f90
gfortran   version.f90
gfortran   input.f90
gfortran   angle.f90
gfortran   readmt.f90
gfortran   readxs.f90
gfortran   readsrc.f90
gfortran   read_inflow.f90
gfortran   check.f90
gfortran   echo.f90
gfortran   solve.f90
gfortran   inner.f90
gfortran   sweep.f90
gfortran   output.f90
gfortran   output_phi.f90
gfortran -lblas -llapack -o ../ahotn1_nefd *.o
rm *.o *.mod
